name: gaming-graphics-core22
version: git
summary: Shared Mesa stack for gaming
description: |
 This snap includes newer versions of Mesa optimized for gaming.
confinement: strict
grade: stable
base: core22
compression: lzo

slots:
    gaming-mesa:
      interface: content
      read:
        - /

package-repositories:
  - type: apt
    # FIXME: We need to enable both 32-bit and 64-bit architectures
    # for this PPA, but Snapcraft doesn't let us do that with the
    # short syntax. So use the full version instead.

    # ppa: kisak/turtle
    url: http://ppa.launchpad.net/kisak/turtle/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [amd64, i386]
    key-id: EB8B81E14DA65431D7504EA8F63F0F2B90935439
    key-server: keyserver.ubuntu.com
  
parts:
  enable-i386:
    plugin: nil
    override-build: |
      craftctl default
      if [ "$CRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
      fi
      apt update

  debs:
    after: [ enable-i386 ]
    plugin: nil
    stage-packages:
      - libvkd3d1:i386
      - libvkd3d1:amd64
      - mesa-va-drivers:amd64
      - mesa-va-drivers:i386
      - mesa-vdpau-drivers:amd64
      - mesa-vdpau-drivers:i386
      - mesa-vulkan-drivers:amd64
      - mesa-vulkan-drivers:i386
      - va-driver-all:amd64
      - va-driver-all:i386
      - va-driver:i386
      - libvdpau-va-gl1:amd64
      - vulkan-tools # For testing/debugging
      - mesa-utils # For testing/debugging
    stage:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/gcc
      - -usr/share/mesa-demos
      - -usr/share/lintian
      - -usr/share/X11
      - -usr/share/bug
      - -usr/share/locale
      - -usr/share/gdb
      - -etc/X11
      - -etc/sensors3.conf
      - -usr/lib/*/gconv
      - -usr/share/gcc
